### ISSUE TITLE
Parsing the Complete Document

### ISSUE THREAD

**Issue by perlmunger** [OpenKitten/BSON#17]
I was able to get the library working on iOS, however, I am using it only for parsing. I took an existing JSON document and converted to BSON using the bsontools. When I load that document into the parser, I only get a single record out even though the JSON had an array of 408 records. I may just be using it wrong, but here's my code:

```
import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var textView: UITextView!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        if let resource = Bundle.main.url(forResource: "categories", withExtension: "bson") {
            if let data = try? Data(contentsOf: resource) {
                let doc = Document(data: data)
                textView.text = "\(doc)"
            }
        }
    }
}
```

Here's what the output looks like in a text view:

![screen shot 2016-10-26 at 3 30 33 pm](https://cloud.githubusercontent.com/assets/17556/19745919/33513b80-9b91-11e6-9d30-a8cfa6e61f55.png)

 and I've attached the BSON and corresponding JSON file for reference:

[categories.zip](https://github.com/OpenKitten/BSON/files/554476/categories.zip)

**Comment by Joannis** [comment]
Document's initializer is for a single document.
We've added an initializer as extension on array for this.
[`[Document](bsonBytes: myArrayOfBytes)`as seen here](https://github.com/OpenKitten/BSON/blob/master/Sources/Document.swift#L24).
It doesn't yet support Foundation.Data in this initializer but that can be added.

**Comment by perlmunger** [comment]
Ah great. Many thanks!
