### ISSUE TITLE
Extraction of Int always fails

### ISSUE THREAD

**Issue by miroslavkovac** [OpenKitten/BSON#18]
I was trying to persist an `Int` value and extract it from `Document`, but the extraction always fails when used with generic `extract<Int>` function.
```
let intValue: Int = 300
var document: BSON.Document = [ "value" : intValue.makeBsonValue() ]
guard let extractedIntValue: Int = document.extract("value") else {
    fatalError("Failed to extract Int.")
}
```

by changing it from platform independent `Int` to any of `Int32` or `Int64` the extraction works fine.

**Comment by Joannis** [comment]
I've got a fix. One second

**Comment by Joannis** [comment]
If you update the BSON dependency it'll work

**Comment by miroslavkovac** [comment]
I which commit did you implement the fix? I am just curious to see it. Thanks.
