### ISSUE TITLE
BSON 5.0 removed StringVariant

### ISSUE THREAD

**Issue by acecilia** [OpenKitten/BSON#25]
Hello:

I saw the new BSON 5.0 included some changes and I want to discuss this one:
![captura de pantalla 2017-04-09 a las 17 01 39](https://cloud.githubusercontent.com/assets/7938671/24838335/7e62bf72-1d46-11e7-9340-f1d3018f43d5.png)

Previously in BSON 4.0 I could create an enum with the string keys for my MongoDB collection objects and pass the enum as a parameter by making it extend the StringVariant protocol:
![captura de pantalla 2017-04-09 a las 17 07 20](https://cloud.githubusercontent.com/assets/7938671/24838374/0835bcb8-1d47-11e7-9bc4-c20093b242be.png)

This provides safety against typo errors and a clearer syntax. 

Is there any possibility to have it back?
If not, could you make the key of the dictionary be a protocol type (so we can extend it) instead of a class or struct type (like String)?

Thanks

**Comment by acecilia** [comment]
I just wrote a post related to it that may give a better explanation of this: https://medium.com/@4ncelu/why-you-should-use-protocol-types-in-the-entry-parameters-of-your-swift-library-instead-of-struct-7e01a8097fb0

**Comment by Obbut** [comment]
Thanks for mentioning this. @Joannis and I discussed this and if possible in a non-breaking way, we'll re-introduce it as a minor update to BSON 5.

**Comment by acecilia** [comment]
@Obbut Nice. I did not look much into StringVariant and I do not know exactly which extra functionality it provides, but to solve this issue a trivial update would be to change String with Custom​String​Convertible

**Comment by Joannis** [comment]
@acecilia It doesn't provide any extra functionality. But there are some cases where updating the initializers to use a protocol rather than a String would cause compiler crashes or causes the compiler to fail recognizing the conformance.

**Comment by Obbut** [comment]
Hey @acecilia, is this still an issue for you or can I close this?

**Comment by acecilia** [comment]
@Obbut Not an issue for now. Closing. Thanks!
