### ISSUE TITLE
BSONEncoder / BSONDecoder

### ISSUE THREAD

**Issue by Evertt** [OpenKitten/BSON#26]
I wasn't sure where to put this, so I thought I'd put it here. Swift 4 will offer a new `Codable` protocol with which you can automagically encode and decode classes and structs to and from data structures such as json. So bson should work too of course, only there's not encode / decoder for that yet.

I would love it if you'd be willing to write a BSON encoder / decoder that works with the codable protocol in Swift 4. Would you be willing to?

**Comment by Joannis** [comment]
Already in the plans!

**Comment by Evertt** [comment]
One more question then. Did you also consider making BSON conform to Vapor's NodeConvertible?

**Comment by Joannis** [comment]
No. We're independent from Vapor, so this is to be done in extensions somehow.

**Comment by Evertt** [comment]
I'm not sure I understand. You also have another repo on this github account which bridges Meow to Fluent, right? So you could make a repo that bridges BSON to Node, right?

**Comment by Joannis** [comment]
We have a bridge from Meow to Vapor (not to Fluent). But in that sense, yes, we will make a BSON + Node helper, it's going to be part of the MongoKitten+Vapor bridge (currently inside MeowVapor). When we feel it's completely mature we'll split it off inside another package for MongoKitten + Vapor users, which includes BSON of course.

**Comment by Joannis** [comment]
@Obbut is working on this now

**Comment by Evertt** [comment]
Awesome! But eh, which one of the two things we discussed here? He's working on the Encoder/Decoder? Or is he working on the Node-bridge?

**Comment by Joannis** [comment]
En/decoding. The node bridge is [here](https://github.com/OpenKitten/MeowVapor/blob/master/Sources/MeowVapor/Node.swift)

**Comment by Obbut** [comment]
You can find [a functional BSONEncoder and BSONDecoder on the swift4 branch](https://github.com/OpenKitten/BSON/blob/swift4/Sources/BSON/Codable.swift). I'm still working on it (the en/decoder and the tests), so don't expect it do work in for all cases yet, but it may already prove useful.

Usage is simple:

```swift
let document = try BSONEncoder().encode(myValue)
let myValue = try BSONDecoder().decode(MyType.self, from: document)
```

`ObjectId` now also supports `Codable` out of the box. It encodes into BSON as an `ObjectId`, and as a hex string into other formats (when using `JSONEncoder`).

**Comment by Evertt** [comment]
Awesome!

**Comment by shanehsu** [comment]
Is there anything lacking in `BSONEncode` and `BSONDecoder` that stands out, would like to help if there's specific goals!

**Comment by Obbut** [comment]
@shanehsu Thanks, but I think it is quite complete now. I'm already using it in a production environment, actually.

I'll close this issue because the feature is implemented. Feel free to open new issues for any questions/problems you might have regarding `BSONEncoder` and `BSONDecoder` 🙂

**Comment by MasterSwift** [comment]
For some reason, BSONEncoder is not being recognized by Xcode. any reason why? I see a large BSONData class that I never saw before

**Comment by Joannis** [comment]
What version of BSON did you depend upon, and how?

**Comment by MasterSwift** [comment]
This was solved. Some files were not in the source folder . After fixing that , doing a quick Clean + build worked.
