### ISSUE TITLE
Doesn't compile using Swift 4.2 compiler

### ISSUE THREAD

**Issue by markltownsend** [OpenKitten/BSON#50]
Still have to set the Swift version to 3.2 when running in Xcode10 and Swift 4.2.  Have a warning that Swift 3 mode is deprecated.  I tried the latest version of 5.2.4 without the Swift 3 mode, and it fails to compile.  Attached a screen snippet of the compiler error.

![image](https://user-images.githubusercontent.com/395903/48572862-7e4a5b80-e8bf-11e8-8887-828289cd6045.png)

**Comment by Joannis** [comment]
Thanks for reporting. We're using Swift 4.2 with no problems, but these are luckily very easy things to solve :)

**Comment by markltownsend** [comment]
Fixed with PR https://github.com/OpenKitten/BSON/pull/56.  Hopefully this could be made into a v5.2.5
