### ISSUE TITLE
Deprecated method warning in Document+Mutation.swift

### ISSUE THREAD

**Issue by mbmshafraz** [OpenKitten/BSON#52]
Document+Mutations.swift:6:17: 'changeCapacity(to:)' is deprecated: changeCapacity has been replaced by reserveCapacity

**Comment by Joannis** [comment]
Yeah, it's a silly issue. SwiftNIO changes that signature in a minor release. I think we can get away with requiring the recent SwiftNIO version now. What do you think @Obbut ?

**Comment by Joannis** [comment]
Thanks for bringing it to our attention again!

**Comment by Obbut** [comment]
I think it's fine to require a more recent version of NIO in our `Package.swift`
