### ISSUE TITLE
Misaligned raw pointer crash when initializing ObjectID

### ISSUE THREAD

**Issue by Andrewangeta** [OpenKitten/BSON#59]
In BSON 7.0 on the master branch, I've saved a document in MongoDB and copied out the raw string from Compass for testing etc.

I try to initialize the ObjectID from the raw string and get a crash
<img width="1699" alt="Screen Shot 2019-07-19 at 9 38 45 PM" src="https://user-images.githubusercontent.com/12012815/61572552-976a6400-aa6d-11e9-82b3-4b37175f2c8e.png">

**Comment by Joannis** [comment]
Thanks again for the report! Fixed
