### ISSUE TITLE
BSON doesn't compile in Swift 5.5 (Xcode 13 beta 4) due to fix for SR-14848

### ISSUE THREAD

**Issue by fritzt0** [OpenKitten/BSON#69]
BSON doesn't compile anymore in Swift 5.5 from Xcode 13 beta 4 due to a fix for [SR-14848](https://bugs.swift.org/browse/SR-14848). From the release notes of Xcode 13 beta 4:

> The Swift standard library no longer provides a nonfunctional default implementation of the subscript(bounds: Range<Index>) accessor for Collection implementors whose SubSequence isn’t Slice. Define your code’s subscript(bounds: Range<Index>) -> SubSequence, or use Slice as your Collection’s SubSequence. (SR-14848, 79891982)

Errors are: 

type 'Document' does not conform to protocol 'RandomAccessCollection'
type 'DocumentSlice' does not conform to protocol 'RandomAccessCollection'

**Comment by Joannis** [comment]
Morning! I heard of the issue before, but I didn't realise it was a change to the standard library. Thanks for informing me!

**Comment by evnik** [comment]
@Joannis Thank you for the fix, could you please push `7.0.28` to CocoaPods, so we can use the latest version in our project?

**Comment by Joannis** [comment]
Done @evnik
