### ISSUE TITLE
I have an idea which can make the ~ prefix operator unnecessary

### ISSUE THREAD

**Issue by Evertt** [OpenKitten/BSON#7]
How about you make `Value` also implement `ValueConvertible`:

```swift
extension Value : ValueConvertible {
    public func makeBsonValue() -> Value {
        return self
    }
}
```

And then you change `BSON/Sources/Document+LiteralConvertibles.swift` so that it accepts a `Dictionary<String, ValueConvertible>` instead of a `Dictionary<String, Value>`.

```swift
extension Document : ArrayLiteralConvertible {
    /// Initialize a Document using an array of `BSONElement`s.
    public init(array: [ValueConvertible]) {
        elements = array.map { ("", $0.makeBsonValue()) }
        self.enforceArray()
    }
    
    /// For now.. only accept BSONElement
    public init(arrayLiteral arrayElements: ValueConvertible...) {
        self.init(array: arrayElements)
    }
    
    public mutating func enforceArray() {
        for i in 0..<elements.count {
            elements[i].0 = "\(i)"
        }
    }
}

extension Document : DictionaryLiteralConvertible {
    public init(dictionaryElements: [(String, ValueConvertible)]) {
        self.elements = dictionaryElements.map { el in (el.0, el.1.makeBsonValue()) }
    }
    
    /// Create an instance initialized with `elements`.
    public init(dictionaryLiteral dictionaryElements: (String, ValueConvertible)...) {
        self.init(dictionaryElements: dictionaryElements)
    }
}
```

Then you don't need to `~` operator anymore for putting variables in a document. You could even go further and change `self.elements` to be of type `[(String, ValueConvertible)]` instead of `[(String, Value)]`. But I don't know how many consequences that has for your code...

What do you think?

**Comment by Joannis** [comment]
There's a slight issue here. But I think that should be invisible to the user.
The issue is that MongoDB doesn't accept `Int64` and `Double` in DBCommands.. which our library heavily uses. But.. If this makes the user experience better it's definitely worth changing this within MongoDB internally and make the three types of numbers practically invisible for the user.

**Comment by Joannis** [comment]
I tried your suggestion. But nested Documents are impossible to use then.
It would just move the problem from variables to nested Documents. I don't think it makes a difference where we use the operator.

**Comment by Evertt** [comment]
Indeed when I try it I get all kinds of errors, but errors that seem to indicate the Swift is confused. In a buggy way. Because for some reason when I implement it then Swift starts seeing `Value` as just a typealias for `ValueConvertible`, but not fully even, because when ever a method requires `Value` and I give it `Value` it says something like *"can't convert ValueConvertible to Value"* even though I didn't give it `ValueConvertible`, I literally gave it `Value`...
